#!/usr/bin/env bash

set -euo pipefail

ROOT=$(cd -- "$(dirname -- "$0")/.." && pwd)
source "$ROOT/config.sh"
source "$ROOT/lib/common.sh"

ensure_directories

run_component "$ROOT/001-runtime/linux-headers"
run_component "$ROOT/001-runtime/glibc"
run_component "$ROOT/001-runtime/gcc-libs"

run_component "$ROOT/001-runtime/zlib"
run_component "$ROOT/001-runtime/xz"
run_component "$ROOT/001-runtime/zstd"
run_component "$ROOT/001-runtime/attr"
run_component "$ROOT/001-runtime/acl"
run_component "$ROOT/001-runtime/libcap"
run_component "$ROOT/001-runtime/libxcrypt"
run_component "$ROOT/001-runtime/lzo"

run_component "$ROOT/001-runtime/libffi"
run_component "$ROOT/001-runtime/pcre2"
run_component "$ROOT/001-runtime/glib"
run_component "$ROOT/001-runtime/libyaml"
run_component "$ROOT/001-runtime/libexif"

run_component "$ROOT/001-runtime/ncurses"
run_component "$ROOT/001-runtime/readline"
run_component "$ROOT/001-runtime/lua"
run_component "$ROOT/001-runtime/duktape"
run_component "$ROOT/001-runtime/alsa-lib"
run_component "$ROOT/001-runtime/ell"
run_component "$ROOT/001-runtime/libnl"
run_component "$ROOT/001-runtime/jansson"
run_component "$ROOT/001-runtime/libndp"
run_component "$ROOT/001-runtime/libarchive"
run_component "$ROOT/001-runtime/fuse"
run_component "$ROOT/001-runtime/sqlite"
run_component "$ROOT/001-runtime/dconf"
run_component "$ROOT/001-runtime/libgpg-error"
run_component "$ROOT/001-runtime/libgcrypt"
run_component "$ROOT/001-runtime/gsettings-desktop-schemas"
run_component "$ROOT/001-runtime/libsecret"

run_component "$ROOT/001-runtime/gmp"
run_component "$ROOT/001-runtime/mpfr"
run_component "$ROOT/001-runtime/json-c"
run_component "$ROOT/001-runtime/popt"
run_component "$ROOT/001-runtime/keyutils"
run_component "$ROOT/001-runtime/libsndfile"

run_component "$ROOT/001-runtime/kmod"
run_component "$ROOT/001-runtime/util-linux"
run_component "$ROOT/001-runtime/e2fsprogs"
run_component "$ROOT/001-runtime/kbd"
run_component "$ROOT/001-runtime/iana-etc"
run_component "$ROOT/001-runtime/tzdata"
run_component "$ROOT/001-runtime/btrfs-progs"
run_component "$ROOT/001-runtime/inih"
run_component "$ROOT/001-runtime/userspace-rcu"
run_component "$ROOT/001-runtime/xfsprogs"
run_component "$ROOT/001-runtime/dosfstools"
run_component "$ROOT/001-runtime/exfatprogs"
run_component "$ROOT/001-runtime/ntfs-3g"
run_component "$ROOT/001-runtime/busybox"
run_component "$ROOT/001-runtime/base-files"
run_component "$ROOT/001-runtime/image"
