#!/usr/bin/env bash

# Global build configuration. Override any value in the environment.
export EFILINUX_ROOT="${EFILINUX_ROOT:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)}"
export EFILINUX_DOWNLOADS="${EFILINUX_DOWNLOADS:-$EFILINUX_ROOT/downloads}"
export EFILINUX_BUILD="${EFILINUX_BUILD:-$EFILINUX_ROOT/build}"
export EFILINUX_TARGET="${EFILINUX_TARGET:-$EFILINUX_ROOT/target}"
export EFILINUX_SYSROOT="${EFILINUX_SYSROOT:-$EFILINUX_BUILD/sysroot}"
export EFILINUX_LOGS="${EFILINUX_LOGS:-$EFILINUX_BUILD/logs}"
export EFILINUX_STATE="${EFILINUX_STATE:-$EFILINUX_BUILD/state}"
export EFILINUX_TEST="${EFILINUX_TEST:-$EFILINUX_BUILD/test}"
export EFILINUX_JOBS="${EFILINUX_JOBS:-$(nproc)}"

export EFILINUX_ARCH="${EFILINUX_ARCH:-x86_64}"
export EFILINUX_KERNEL_ARCH="${EFILINUX_KERNEL_ARCH:-x86}"
export EFILINUX_X86_64_LEVEL="${EFILINUX_X86_64_LEVEL:-x86-64-v2}"

# Pinned from the latest stable LFS package set used by this stage.
export LINUX_VERSION="${LINUX_VERSION:-6.18.10}"
export LINUX_MD5="${LINUX_MD5:-660e706a43f634b1fcd911f8839d2f61}"
export GLIBC_VERSION="${GLIBC_VERSION:-2.43}"
export GLIBC_MD5="${GLIBC_MD5:-7ec2588300b299215a65aec7e6afa04f}"

# BusyBox is not in LFS; it is the deliberate minimal-userland exception.
export BUSYBOX_VERSION="${BUSYBOX_VERSION:-1.37.0}"
export BUSYBOX_SHA256="${BUSYBOX_SHA256:-3311dff32e746499f4df0d5df04d7eb396382d7e108bb9250e7b519b837043a4}"

export EFILINUX_INITRAMFS_DEVICES="${EFILINUX_INITRAMFS_DEVICES:-$EFILINUX_BUILD/initramfs.devices}"
export EFILINUX_KERNEL_BUILD="${EFILINUX_KERNEL_BUILD:-$EFILINUX_BUILD/linux-$LINUX_VERSION}"
export EFILINUX_EFI_DIR="${EFILINUX_EFI_DIR:-$EFILINUX_TARGET/efi}"
