#!/usr/bin/env bash

# Global build configuration. Override any value in the environment.
export EFILINUX_ROOT="${EFILINUX_ROOT:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)}"
export EFILINUX_DOWNLOADS="${EFILINUX_DOWNLOADS:-$EFILINUX_ROOT/downloads}"
export EFILINUX_PACKAGES="${EFILINUX_PACKAGES:-$EFILINUX_ROOT/packages}"
export EFILINUX_BUILD="${EFILINUX_BUILD:-$EFILINUX_ROOT/build}"
export EFILINUX_TARGET="${EFILINUX_TARGET:-$EFILINUX_ROOT/target}"
export EFILINUX_ROOTFS="${EFILINUX_ROOTFS:-$EFILINUX_TARGET/rootfs}"
export EFILINUX_SYSROOT="${EFILINUX_SYSROOT:-$EFILINUX_BUILD/sysroot}"
export EFILINUX_LOGS="${EFILINUX_LOGS:-$EFILINUX_BUILD/logs}"
export EFILINUX_STATE="${EFILINUX_STATE:-$EFILINUX_BUILD/state}"
export EFILINUX_TEST="${EFILINUX_TEST:-$EFILINUX_BUILD/test}"
export EFILINUX_ROOTFS_OWNERS="${EFILINUX_ROOTFS_OWNERS:-$EFILINUX_STATE/rootfs-owners.tsv}"
export EFILINUX_ROOTFS_FAKEROOT_STATE="${EFILINUX_ROOTFS_FAKEROOT_STATE:-$EFILINUX_STATE/rootfs.fakeroot}"
export EFILINUX_PACKAGE_INDEX="${EFILINUX_PACKAGE_INDEX:-$EFILINUX_PACKAGES/index.tsv}"
export EFILINUX_PACKAGE_WORK="${EFILINUX_PACKAGE_WORK:-$EFILINUX_BUILD/packages}"
export EFILINUX_JOBS="${EFILINUX_JOBS:-$(nproc)}"

export EFILINUX_ARCH="${EFILINUX_ARCH:-x86_64}"
export EFILINUX_KERNEL_ARCH="${EFILINUX_KERNEL_ARCH:-x86}"
export EFILINUX_X86_64_LEVEL="${EFILINUX_X86_64_LEVEL:-x86-64-v2}"
export EFILINUX_TOOLCHAIN_TRIPLET="${EFILINUX_TOOLCHAIN_TRIPLET:-}"

export EFILINUX_INITRAMFS_MANIFEST="${EFILINUX_INITRAMFS_MANIFEST:-$EFILINUX_BUILD/initramfs.files}"
export EFILINUX_EFI_DIR="${EFILINUX_EFI_DIR:-$EFILINUX_TARGET/efi}"
