#!/usr/bin/sh
set -eu
. /etc/rc.d/init.d/functions

start_graphical() {
    mkdir -p /run/user/1000 /tmp/.X11-unix /var/cache/fontconfig /var/lib/xkb
    chown 1000:1000 /run/user/1000
    chmod 0700 /run/user/1000
    chmod 1777 /tmp/.X11-unix

    start_daemon graphical \
        /usr/bin/su user -c \
        'exec env DISPLAY=:0 GDK_BACKEND=x11 HOME=/home/user LOGNAME=user PATH=/usr/bin USER=user XAUTHORITY=/home/user/.Xauthority XDG_RUNTIME_DIR=/run/user/1000 /usr/bin/startx /etc/X11/xinit/xinitrc -- /usr/bin/Xorg :0 -nolisten tcp -noreset' \
        >>/var/log/graphical.log 2>&1
}

case ${1:-} in
    start) start_graphical ;;
    stop) stop_daemon graphical ;;
    *) printf 'usage: %s {start|stop}\n' "$0" >&2; exit 2 ;;
esac
