#!/usr/bin/env bash
set -euo pipefail

ROOT=$(cd -- "$(dirname -- "$0")/.." && pwd)
source "$ROOT/config.sh"
source "$ROOT/lib/common.sh"

run_component "$ROOT/005-applications/libsigcxx"
run_component "$ROOT/005-applications/glibmm"
run_component "$ROOT/005-applications/cairomm"
run_component "$ROOT/005-applications/pangomm"
run_component "$ROOT/005-applications/atkmm"
run_component "$ROOT/005-applications/gtkmm"
run_component "$ROOT/005-applications/gtksourceview4"
run_component "$ROOT/005-applications/json-glib"
run_component "$ROOT/005-applications/openjpeg"
run_component "$ROOT/005-applications/poppler"
run_component "$ROOT/005-applications/epdfview"
run_component "$ROOT/005-applications/ffmpeg-libs"
run_component "$ROOT/005-applications/gstreamer"
run_component "$ROOT/005-applications/gst-plugins-base"
run_component "$ROOT/005-applications/gst-plugins-good"
run_component "$ROOT/005-applications/gst-plugins-bad"
run_component "$ROOT/005-applications/gst-libav"
run_component "$ROOT/005-applications/parole"
run_component "$ROOT/005-applications/libsodium"
run_component "$ROOT/005-applications/freerdp"
run_component "$ROOT/005-applications/libssh"
run_component "$ROOT/005-applications/libvncserver"
run_component "$ROOT/005-applications/spice-protocol"
run_component "$ROOT/005-applications/spice-gtk"
run_component "$ROOT/005-applications/remmina"
run_component "$ROOT/005-applications/xarchiver"
run_component "$ROOT/005-applications/mousepad"
run_component "$ROOT/005-applications/ristretto"
run_component "$ROOT/005-applications/pavucontrol"
run_component "$ROOT/005-applications/xfce4-taskmanager"
run_component "$ROOT/005-applications/xfce4-screenshooter"
run_component "$ROOT/005-applications/thunar-archive-plugin"
run_component "$ROOT/005-applications/galculator"
run_component "$ROOT/005-applications/gparted"
run_component "$ROOT/005-applications/efilinux-live-manager"
run_component "$ROOT/005-applications/image"
