#!/bin/sh

export LANG="${LANG:-en_US.UTF-8}"
export XDG_CONFIG_DIRS="/etc/xdg"
export XDG_DATA_DIRS="/usr/local/share:/usr/share"
export XCURSOR_THEME="Qogir"
export XCURSOR_SIZE="24"

exec /usr/bin/dbus-run-session -- /usr/bin/startxfce4
