#!/usr/bin/sh
set -eu

export GDK_BACKEND=x11
export XDG_CONFIG_DIRS="/opt/fcitx5/etc/xdg:/etc/xdg"
export GTK_IM_MODULE=fcitx
export GTK_IM_MODULE_FILE=/opt/fcitx5/etc/gtk-3.0/gtk.immodules
export GTK_PATH=/opt/fcitx5/lib/gtk-3.0
export QT_IM_MODULE=xim
export XMODIFIERS=@im=fcitx
export SDL_IM_MODULE=fcitx
export NO_AT_BRIDGE=0
export XDG_RUNTIME_DIR=/run/user/0

exec /usr/bin/dbus-run-session -- /usr/bin/sh -c 'while :; do /usr/bin/sleep 3600; done'
