#!/usr/bin/sh
set -eu

export GDK_BACKEND=x11
export XDG_CONFIG_DIRS="/opt/fcitx5/etc/xdg:/etc/xdg"
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=xim
export XMODIFIERS=@im=fcitx
export SDL_IM_MODULE=fcitx
export NO_AT_BRIDGE=0

exec /usr/bin/dbus-run-session -- /usr/bin/sh -c 'while :; do /usr/bin/sleep 3600; done'
