#!/usr/bin/sh
set -eu
. /etc/rc.d/init.d/functions

start_graphical() {
    mkdir -p /run/user/0 /tmp/.X11-unix /var/cache/fontconfig /var/lib/xkb
    chmod 0700 /run/user/0
    chmod 1777 /tmp/.X11-unix

    export DISPLAY=:0
    export GDK_BACKEND=x11
    export HOME=/root
    export LOGNAME=root
    export PATH=/usr/bin
    export USER=root
    export XAUTHORITY=/root/.Xauthority
    export XDG_RUNTIME_DIR=/run/user/0

    start_daemon graphical \
        /usr/bin/startx /etc/X11/xinit/xinitrc -- \
        /usr/bin/Xorg :0 -nolisten tcp -noreset \
        >>/var/log/graphical.log 2>&1
}

case ${1:-} in
    start) start_graphical ;;
    stop) stop_daemon graphical ;;
    *) printf 'usage: %s {start|stop}\n' "$0" >&2; exit 2 ;;
esac
