#!/usr/bin/sh
set -eu
. /etc/rc.d/init.d/functions

case ${1:-} in
    start)
        mkdir -p /run/dhcpcd /var/lib/dhcpcd
        start_daemon dhcpcd dhcpcd -B -f /etc/dhcpcd.conf
        ;;
    stop) stop_daemon dhcpcd ;;
    *) printf 'usage: %s {start|stop}\n' "$0" >&2; exit 2 ;;
esac
