#!/usr/bin/sh
set -eu
. /etc/rc.d/init.d/functions

case ${1:-} in
    start)
        mkdir -p /run/elogind /run/systemd /run/user /var/lib/elogind
        chmod 0755 /run/elogind /run/systemd /run/user /var/lib/elogind
        start_daemon elogind /usr/libexec/elogind
        ;;
    stop) stop_daemon elogind ;;
    *) printf 'usage: %s {start|stop}\n' "$0" >&2; exit 2 ;;
esac
