#!/usr/bin/sh
set -eu
. /etc/rc.d/init.d/functions

case ${1:-} in
    start)
        mkdir -p /var/lib/upower
        chown upower:upower /var/lib/upower
        start_daemon upower /usr/libexec/upowerd
        ;;
    stop) stop_daemon upower ;;
    *) printf 'usage: %s {start|stop}\n' "$0" >&2; exit 2 ;;
esac
